

CREATE TABLE T_EV_9 (
	ID INTEGER NOT NULL,
	ID_OBJ INTEGER NOT NULL,
	REGDATE TIMESTAMP NOT NULL,
	XI_1 INTEGER,
	XI_2 INTEGER,
	XI_3 INTEGER,
	XI_4 INTEGER,
	XI_5 INTEGER,
	XR_1 DOUBLE PRECISION,
	XR_2 DOUBLE PRECISION,
	XR_3 DOUBLE PRECISION,
	XR_4 DOUBLE PRECISION,
	XR_5 DOUBLE PRECISION,
	XS10_1 VARCHAR(10),
	XS10_2 VARCHAR(10),
	XS10_3 VARCHAR(15),
	XS10_4 VARCHAR(10),
	XS10_5 VARCHAR(10),
	XS100_1 VARCHAR(100),
	XS100_2 VARCHAR(100),
	XS100_3 VARCHAR(100),
	XS100_4 VARCHAR(100),
	XS100_5 VARCHAR(100),
	XRS_1 VARCHAR(20),
	XRS_2 VARCHAR(20),
	XRS_3 VARCHAR(20),
	XD_1 TIMESTAMP,
	XD_2 TIMESTAMP,
	ID_GRP INTEGER NOT NULL,
	ID_T_PD_CMS INTEGER NOT NULL,
	ID_USER INTEGER,
	ID_CG INTEGER,
	ID_ZANCG INTEGER,
	PRIMARY KEY (ID)
);
CREATE INDEX T_EV_9_G_COD ON T_EV_9 (XS10_3);
CREATE INDEX T_EV_9_IDCG ON T_EV_9 (ID_CG);
CREATE INDEX T_EV_9_ID_GRP ON T_EV_9 (ID_GRP);
CREATE INDEX T_EV_9_ID_OBJ ON T_EV_9 (ID_OBJ);
CREATE INDEX T_EV_9_ID_T_PD_CMS ON T_EV_9 (ID_T_PD_CMS);
CREATE INDEX T_EV_9_ID_US ON T_EV_9 (ID_USER);
CREATE INDEX T_EV_9_REG_DATE ON T_EV_9 (REGDATE);
CREATE INDEX T_EV_9_XI_2 ON T_EV_9 (XI_2);
CREATE UNIQUE INDEX UNQ1_T_EV_9 ON T_EV_9 (ID_OBJ,XI_2,XI_4);
