#!/usr/bin/env sh
set -e

cd "$(dirname "$0")"
export ISC_PASSWORD=${ISC_PASSWORD:-test}
export FIREBIRD_DATABASE=${FIREBIRD_DATABASE:-dekanat.fdb}
export FIREBIRD_BACKUP_FILE="${FIREBIRD_BACKUP_FILE:-"dekanat.fbk"}"

/usr/local/firebird/docker-entrypoint.sh firebird &
sleep 0.5
NEXT_WAIT_TIME=0
until nc -z 127.0.0.1 3050; do
  sleep 0.5
  NEXT_WAIT_TIME=$((NEXT_WAIT_TIME+1))
  [ $NEXT_WAIT_TIME -eq 10 ] && echo "Firebird not started" && exit 10
done

for file in schema/*.sql; do
  "${PREFIX}/bin/isql" -u sysdba -p "$ISC_PASSWORD" "$FIREBIRD_DATABASE" -i "$file"
  echo "Done $file - exit code: $?"
done

"${PREFIX}/bin/gbak" -b -user sysdba -password "$ISC_PASSWORD" "$FIREBIRD_DATABASE" "$FIREBIRD_BACKUP_FILE"

ls -lah "${FIREBIRD_BACKUP_FILE}"
