name: Build docker image

on:
  push:
    branches: ['main']

jobs:
  make-fbk:
    runs-on: ubuntu-latest
    container:
      image: jacobalberty/firebird:v4.0
    steps:
      - uses: actions/checkout@v3
      - name: Make fbk
        run: ./make-fbk
      - uses: actions/upload-artifact@v3
        with:
          name: dekanat.fbk
          path: dekanat.fbk

  build:
    needs: make-fbk
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dekanat.fbk

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
